### ISSUE TITLE
"index out of bounds", when cycling past the outer columns

### ISSUE THREAD

**Issue by pflakus** [bvaisvil/zenith#96]
When I press `.` or `,` in the task panel, to move the selected column past the first/last column, the application fails with the following "index out of bounds"-message:
```
$ zenith
thread '<unnamed>' panicked at 'index out of bounds: the len is 12 but the index is 13', src/render.rs:314:5
```

The issue can be reproduced consistently.
I'm running `zenith 0.12.0`, from the "zenith-bin" AUR package.

**Comment by bvaisvil** [comment]
Thanks for reporting!

**Comment by bvaisvil** [comment]
Unable to replicate on my end as of yet. Are you running with nvidia/graphics support?

**Comment by pflakus** [comment]
Without, I don't have the optional "nvidia-tools" installed.

To be clear, I was just trying this tool out for fun, to compare Rust-based tool alternatives. But I moved on in the meantime. (No hard feelings, I hope... ;) ) I just reported it hoping that it would be helpful to you.
So if this bug doesn't impact more users, feel free to deprioritize this issue...

But for reference, I just did another clean install (without nvidia support) and was able to reproduce the same behavior instantly.

**Comment by bvaisvil** [comment]
Thanks for getting back to me. And no, no hard feelings :). I appreciate you took to the time to make an issue and get back to me.

**Comment by murlakatamenka** [comment]
Hey, I can reproduce the issue. No nvidia GPU here. 

zenith panics if you jump

1. beyond rightmost column with `.`:

```sh
thread '<unnamed>' panicked at 'index out of bounds: the len is 12 but the index is 12', src/render.rs:314:5
```
2. beyond leftmost column with `,`:

```sh
thread '<unnamed>' panicked at 'index out of bounds: the len is 12 but the index is 13', src/render.rs:314:5
```

(I'm the maintainer of the aforementioned AUR `zenith-bin` package btw :smile: and also have it installed)

**Comment by bvaisvil** [comment]
Thanks for letting me know. What version are you running ?

**Comment by murlakatamenka** [comment]
Latest release, 0.12.0:

https://dl.bintray.com/bvaisvil/debian/pool/z/zenith/zenith_0.12.0-1_amd64.deb

**Comment by bvaisvil** [comment]
Possible for you to try building it from source (master branch) and see if it still happens for you?

**Comment by murlakatamenka** [comment]
It _cycles_ as expected with current master 6f09825

**Comment by bvaisvil** [comment]
great! Thank you for testing and letting me know. I'll work on making a new release.

**Comment by murlakatamenka** [comment]
I maintain AUR's `zenith` and  `zenith-bin` packages and found something interesting:

zenith 0.13 complied from sources doesn't have this OOB panic, but binary from .deb release does.

![image](https://user-images.githubusercontent.com/7361274/157769651-96dd6d8d-9c2a-454f-b7eb-8a97636886ee.png)

**Comment by bvaisvil** [comment]
@murlakatamenka Thanks for reporting! I'll take a look.

**Comment by bvaisvil** [comment]
Does it panic instantly, or only while cycling? If it panics while you're cycling the table, could you tell me what columns you have?

**Comment by bvaisvil** [comment]
I've made a new deb package that contains the fixes in commit [897364e](https://github.com/bvaisvil/zenith/commit/897364e2f0549397149bcdac3d4c549f07f6d3eb). In my testing this fixed the issue. Would very much appreciate it if you could give it a try and see if it works for you.

New Deb file:
[zenith_0.13.0-1_amd64.deb.zip](https://github.com/bvaisvil/zenith/files/8235927/zenith_0.13.0-1_amd64.deb.zip)

**Comment by murlakatamenka** [comment]
> Does it panic instantly, or only while cycling? If it panics while you're cycling the table, could you tell me what columns you have?

Yes, it was only when cycling.

![image](https://user-images.githubusercontent.com/7361274/158011181-3a673c4d-5e8a-405c-821f-5f474248bc03.png)

---

Your guess should be right because I don't run Nvidia GPU and don't have its drivers installed. The binary from attached .deb works without panicking :+1: 

As a side note it still shows an empty "Graphics" group, it takes space for no reason.

**Comment by bvaisvil** [comment]
> As a side note it still shows an empty "Graphics" group, it takes space for no reason.

Updated to hide the 'Graphics' group to hide if no cards are detected. Could you try this and check to see if that works and if it still doesn't crash. Thanks!

[zenith_0.13.0-1_amd64.deb.zip](https://github.com/bvaisvil/zenith/files/8257593/zenith_0.13.0-1_amd64.deb.zip)
